---
title: "L03: G-computation with NAMCS"
author: "EPID 722, 2016"
date: "January 19, 2016"
output: html_document
---

### Specify packages

```{r}
#install.packages(c("foreign", "foreach"))
library(knitr)
library(foreign)
library(foreach)
```

```{r setup, echo=FALSE}
opts_chunk$set(root.dir = 'C:/Users/vonholle/Dropbox/unc.grad.school.2016.spring/epid.722/data')
```

### Read in NAMCS data -- will need to correct the path

```{r}
ns=read.dta("c:/temp/nsaid008.dta") #NOTE: path has to have forward slashes 
```

### Is there evidence of confounding?

```{r}
covs=c("male","age","diabetes","arthrtis","copd","contppi",
       "reas1digest","tobacco_imp","contsteroids")
ret=foreach(var=covs,.combine="rbind") %do%
  tapply(ns[,var],ns$newcox2,mean)

row.names(ret)<-covs
colnames(ret)<-c("Old NSAIDS","Cox-2 Sel NSAIDs")
round(ret,2)
```

### Simulate outcome using logistic regression

```{r}
ns$pbleed=1/(1+exp(-(-6.75 + .6*ns$contanticoag + 1*ns$tobacco_imp + .5*ns$contsteroids + 
                    .2*ns$contaspirin + .7*ns$arthrtis + .07*ns$age + .3*ns$male + 
                    .02*ns$raceblkoth- .3*ns$newcox2 )))

ns$bleed=rbinom(size=1,n=nrow(ns),p=ns$pbleed)
```

### What is E[Y(1)]-E[Y(0)], causal risk difference

```{r}
pbleed.0=1/(1+exp(-(-6.75 + .6*ns$contanticoag + 1*ns$tobacco_imp + .5*ns$contsteroids + 
                       .2*ns$contaspirin + .7*ns$arthrtis + .07*ns$age + .3*ns$male + 
                       .02*ns$raceblkoth)))

pbleed.1=1/(1+exp(-(-6.75 + .6*ns$contanticoag + 1*ns$tobacco_imp + .5*ns$contsteroids + 
                      .2*ns$contaspirin + .7*ns$arthrtis + .07*ns$age + .3*ns$male + 
                      .02*ns$raceblkoth - 0.3)))

mean(pbleed.1)-mean(pbleed.0)
```

### What is E[Y(1)]/E[Y(0)]? causal risk ratio

```{r}
mean(pbleed.1)/mean(pbleed.0)
```

### What is E[Y(1)|X=1]-E[Y(0)|X=1]?

```{r}
mean(pbleed.1[ns$newcox2==1])-mean(pbleed.0[ns$newcox2==1])
```

### What is E[Y(1)|X=1]-E[Y(0)|contanticoag=1]?

```{r}
mean(pbleed.1[ns$contanticoag==1])-mean(pbleed.0[ns$contanticoag==1])
```

### What is E[Y(treat on if on warfarin)]-E[Y(0)]?

```{r}
newtreat=ifelse(ns$contanticoag==1,1,0)

pbleed.0=1/(1+exp(-(-6.75 + .6*ns$contanticoag + 1*ns$tobacco_imp + .5*ns$contsteroids + 
                      .2*ns$contaspirin + .7*ns$arthrtis + .07*ns$age + .3*ns$male + 
                      .02*ns$raceblkoth)))

pbleed.1=1/(1+exp(-(-6.75 + .6*ns$contanticoag + 1*ns$tobacco_imp + .5*ns$contsteroids + 
                      .2*ns$contaspirin + .7*ns$arthrtis + .07*ns$age + .3*ns$male + 
                      .02*ns$raceblkoth - 0.3*newtreat)))

mean(pbleed.1)-mean(pbleed.0)
```

### Estimate E[Y(1)]-E[Y(0)] with MLE?

```{r}
glm.out=glm(bleed~contanticoag+tobacco_imp+contsteroids+contaspirin+arthrtis+age+male+raceblkoth+newcox2,family=binomial,data=ns)
ns.temp=ns
ns.temp$newcox2=0
pbleed.0=predict(glm.out,newdata=ns.temp,type="response")
ns.temp$newcox2=1
pbleed.1=predict(glm.out,newdata=ns.temp,type="response")

mean(pbleed.1)-mean(pbleed.0)
```
