---
title: "Advanced Epidemiologic Methods, EPID 722"
date: "September 8, 2015"
output: html_document
---

**Objective**:	Upon completion of this course learners will be better able to solve problems in epidemiologic research regarding the planning, analysis, and interpretation of complex studies.

**Description**:	This course covers state-of-the-science epidemiologic methods. We concentrate on methods based on sound theoretical principles which maximize the accuracy of inferences drawn from analyses of complex randomized and nonrandomized (observational) studies. We discuss a series of topics using assigned readings and programs written in SAS and R. Students will work in groups on a course project.

**Instructors**:	M. Alan Brookhart (mabrook@email.unc.edu)
Stephen R. Cole (cole@unc.edu), 919-966-7415

**TAs**:		Sydney Jones (sydneyaj@email.unc.edu)
Ann Von Holle (vonholle@email.unc.edu)

**Dates/Times**:	Spring semester, Tuesdays and Thursdays, 12:30 - 1:45pm.
		Recitation on Mondays, 1:25-2:15

**Room**:		McGG 2308

**Office hours**: 	TBA

**Prerequisites**:	Prior knowledge of epidemiologic and statistical methods (e.g., successful completion of EPID 718), as well as a working knowledge of SAS or R.

**Grading**:	The course grade is based 40% on a midterm examination and 60% on a project, split equally across 4 deliverables (see course plan). The scale is H > 90, P = 70 - 90, L = 60 - 69, and F < 60. Your full participation and observance of the UNC-Chapel Hill honor code is expected [Honor system](https://studentconduct.unc.edu/honor-system).
