---
title: "EPID 722 Course plan"
output: html_document
---

EPID 722 Course plan:


| Date          | Topic (readings --refer to list at bottom of page)                    |                   |
|---------------|-------------------------------------|-------------------|
| Tuesday 1/12  | Course preview and Risk (1)         | Brookhart/Cole    |
| Thursday 1/14 | Counterfactuals, design and confounding | Brookhart         |
| Tuesday 1/19  | IP-weighting and propensity scores    | Brookhart         |
| Thursday 1/21 | The g formula  | Brookhart         |
| Tuesday  1/26 | Simulation                       | Brookhart         |
| Thursday 1/28 | Bootstrap                           | Brookhart         |
| Tuesday 2/2   | Maximum likelihood (2)       | Cole              |
| Thursday 2/4  | Bayesian inference (3)      | Cole              |
| Tuesday 2/9   | Survival functions (4)         | Cole              |
| Thursday 2/11 | IP-weighted survival functions (5)  | Cole         |
| Tuesday 2/16  | IP-weighted Cox models (6)                       | Cole              |
| Thursday 2/18 | Generalizability (7)             | Cole              |
| Tuesday 2/23  | Missing data (8)        | Cole              |
| Thursday 2/25 | Smoothing and splines | Brookhart              |
| Tuesday 3/1   | Open session<sup>1</sup>                       | TBN               |
| Thursday 3/3  | Exam preview                        | Brookhart/Cole    |
| Tuesday 3/8   | Exam                                |                   |
| Thursday 3/10 | Exam review                         | Brookhart/Cole    |
| SPRING        |                                     |                   |
| BREAK         |                                     |                   |
| Tuesday 3/22  | Project                             |                   |
| Thursday 3/24 | Double-robust                      | Jonsson-Funk               |
| Tuesday 3/29  | Project                             |                   |
| Thursday 3/31 | Competing risks                       | Edwards, Table 1 due  |
| Tuesday 4/5   | Project                             |                   |
| Thursday 4/7  | G formula with time-varying treatments                       | Keil, Table 2 due  |
| Tuesday 4/12  | Project                             |                   |
| Thursday 4/14 | Open session<sup>1</sup>                       | Westreich, Figure 1 due |
| Tuesday 4/19  | Project                             |                   |
| Thursday 4/21 | Open session<sup>1</sup>                       | TBN, Abstract due |
| Tuesday 4/26  | Course review                       |                   |

<sup>1</sup> Open sessions will be used to cover advanced topics<sup>2</sup>, and accommodate snow days if needed.

<sup>2</sup> List of advanced topics include: covariate/model choice, generalizability, instrumental variables, measurement error, structural nested models.

---

**Readings**

    Cole SR, Hudgens MG, Brookhart MA, et al. Risk. Am. J. Epidemiol. [electronic article]. 2015;181(4):246–250. (http://aje.oxfordjournals.org/cgi/doi/10.1093/aje/kwv001).
    
    Cole SR, Chu H, Greenland S. Maximum Likelihood, Profile Likelihood, and Penalized Likelihood: A Primer. Am. J. Epidemiol. [electronic article]. 2014;179(2):252–260. (http://aje.oxfordjournals.org/cgi/doi/10.1093/aje/kwt245).
    
    Cole SR, Chu H, Greenland S, et al. Bayesian Posterior Distributions Without Markov Chains. Am. J. Epidemiol. [electronic article]. 2012;175(5):368–375. (http://aje.oxfordjournals.org/cgi/doi/10.1093/aje/kwr433).
    
    Cole SR, Stuart EA. Generalizing Evidence From Randomized Clinical Trials to Target Populations: The ACTG 320 Trial. Am. J. Epidemiol. [electronic article]. 2010;172(1):107–115. (http://aje.oxfordjournals.org/cgi/doi/10.1093/aje/kwq084).
    
    Cole SR, Hernán MA. Adjusted survival curves with inverse probability weights. Comput. Methods Programs Biomed. [electronic article]. 2004;75(1):45–49. (http://linkinghub.elsevier.com/retrieve/pii/S0169260703001378).
    
    Buchanan AL, Hudgens MG, Cole SR, et al. Worth the Weight: Using Inverse Probability Weighted Cox Models in AIDS Research. AIDS Res. Hum. Retroviruses [electronic article]. 2014;30(12):1170–1177. (http://online.liebertpub.com/doi/abs/10.1089/aid.2014.0037).
    
    Cole SR, Hudgens MG. Survival analysis in infectious disease research: Describing events in time: AIDS [electronic article]. 2010;24(16):2423–2431. (http://content.wkhealth.com/linkback/openurl?sid=WKPTLP:landingpage&an=00002030-201010230-00001).
    
    Greenland S, Finkle WD. A critical look at methods for handling missing covariates in epidemiologic regression analyses. Am. J. Epidemiol. 1995;142(12):1255–1264.
